"""empty message

Revision ID: 703571b2121
Revises: 48ecf8e22805
Create Date: 2015-08-14 15:41:59.490336

"""

# revision identifiers, used by Alembic.
revision = '703571b2121'
down_revision = '48ecf8e22805'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
