"""empty message

Revision ID: 10ff0e109a5c
Revises: 4f1c7d90dfcb
Create Date: 2015-08-13 09:41:36.835483

"""

# revision identifiers, used by Alembic.
revision = '10ff0e109a5c'
down_revision = '4f1c7d90dfcb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ncbi_collection_piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], ['ncbi_piece.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'ncbi_piece_ibfk_1', 'ncbi_piece', type_='foreignkey')
    op.drop_column(u'ncbi_piece', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'ncbi_piece', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'ncbi_piece_ibfk_1', 'ncbi_piece', 'user', ['user_id'], ['id'])
    op.drop_table('ncbi_collection_piece')
    ### end Alembic commands ###
