"""empty message

Revision ID: 3f0c256ca00e
Revises: 1cf6e228f40b
Create Date: 2015-07-26 10:52:12.175894

"""

# revision identifiers, used by Alembic.
revision = '3f0c256ca00e'
down_revision = '1cf6e228f40b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'user', 'published_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'user', 'published_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_table('follow')
    ### end Alembic commands ###
