"""empty message

Revision ID: 3da9f0048412
Revises: 3d3f9ef54a5e
Create Date: 2015-07-23 18:27:35.346059

"""

# revision identifiers, used by Alembic.
revision = '3da9f0048412'
down_revision = '3d3f9ef54a5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('published', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece', 'published')
    ### end Alembic commands ###
