"""empty message

Revision ID: 58e19ada9ee5
Revises: 49086f55444e
Create Date: 2015-07-21 16:23:24.026509

"""

# revision identifiers, used by Alembic.
revision = '58e19ada9ee5'
down_revision = '49086f55444e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blog', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('douban', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('introduction', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('liked_collections_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('motto', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('pieces_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('votes_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('weibo', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('zhihu', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zhihu')
    op.drop_column('user', 'weibo')
    op.drop_column('user', 'votes_count')
    op.drop_column('user', 'pieces_count')
    op.drop_column('user', 'motto')
    op.drop_column('user', 'liked_collections_count')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'introduction')
    op.drop_column('user', 'douban')
    op.drop_column('user', 'blog')
    ### end Alembic commands ###
