"""empty message

Revision ID: 4f23a52f6974
Revises: 703571b2121
Create Date: 2015-08-14 16:31:01.756170

"""

# revision identifiers, used by Alembic.
revision = '4f23a52f6974'
down_revision = '703571b2121'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
