"""empty message

Revision ID: 66cc631bdc4
Revises: 2f5755a72d88
Create Date: 2015-07-29 19:43:30.715362

"""

# revision identifiers, used by Alembic.
revision = '66cc631bdc4'
down_revision = '2f5755a72d88'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('sender_deleted', sa.Boolean(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('receiver_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('messsage')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messsage',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.TEXT(collation=u'utf8_unicode_ci'), nullable=True),
    sa.Column('checked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('checked_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('receiver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('receiver_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('sender_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], [u'user.id'], name=u'messsage_ibfk_1'),
    sa.ForeignKeyConstraint(['sender_id'], [u'user.id'], name=u'messsage_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('message')
    ### end Alembic commands ###
