"""empty message

Revision ID: 5f6ddf4084f
Revises: 248f57a24bc6
Create Date: 2015-08-26 20:56:54.897192

"""

# revision identifiers, used by Alembic.
revision = '5f6ddf4084f'
down_revision = '248f57a24bc6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncbi_piece', sa.Column('in_pmc', sa.Boolean(), nullable=True))
    op.add_column('ncbi_piece', sa.Column('pmc_uid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ncbi_piece', 'pmc_uid')
    op.drop_column('ncbi_piece', 'in_pmc')
    ### end Alembic commands ###
