"""empty message

Revision ID: 2f5755a72d88
Revises: 36a4ec2b6f43
Create Date: 2015-07-29 19:38:30.061877

"""

# revision identifiers, used by Alembic.
revision = '2f5755a72d88'
down_revision = '36a4ec2b6f43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messsage', sa.Column('receiver_deleted', sa.Boolean(), nullable=False))
    op.add_column('messsage', sa.Column('sender_deleted', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messsage', 'sender_deleted')
    op.drop_column('messsage', 'receiver_deleted')
    ### end Alembic commands ###
