"""empty message

Revision ID: 485b89802f79
Revises: 5678988f31e4
Create Date: 2015-08-14 16:32:52.076642

"""

# revision identifiers, used by Alembic.
revision = '485b89802f79'
down_revision = '5678988f31e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncbi_piece', sa.Column('pub_date', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ncbi_piece', 'pub_date')
    ### end Alembic commands ###
