"""empty message

Revision ID: 48ecf8e22805
Revises: 10ff0e109a5c
Create Date: 2015-08-13 10:50:36.646770

"""

# revision identifiers, used by Alembic.
revision = '48ecf8e22805'
down_revision = '10ff0e109a5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
