"""empty message

Revision ID: 248f57a24bc6
Revises: 485b89802f79
Create Date: 2015-08-26 16:14:19.695057

"""

# revision identifiers, used by Alembic.
revision = '248f57a24bc6'
down_revision = '485b89802f79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncbi_piece', sa.Column('abstract', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ncbi_piece', 'abstract')
    ### end Alembic commands ###
