"""empty message

Revision ID: 5678988f31e4
Revises: 4f23a52f6974
Create Date: 2015-08-14 16:32:14.149394

"""

# revision identifiers, used by Alembic.
revision = '5678988f31e4'
down_revision = '4f23a52f6974'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ncbi_piece', 'pub_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncbi_piece', sa.Column('pub_date', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
