"""empty message

Revision ID: 4f1c7d90dfcb
Revises: 394b4b86f6d7
Create Date: 2015-08-13 09:17:13.215246

"""

# revision identifiers, used by Alembic.
revision = '4f1c7d90dfcb'
down_revision = '394b4b86f6d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ncbi_piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('db_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('pub_journal', sa.String(length=100), nullable=True),
    sa.Column('pub_journal_page', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('ncbipieces_count', sa.Integer(), nullable=False, default=0))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'ncbipieces_count')
    op.drop_table('ncbi_piece')
    ### end Alembic commands ###
